// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'No Firebase options configured for web platform.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'sua-api-key-aqui',
    appId: 'seu-app-id-aqui',
    messagingSenderId: 'seu-messaging-sender-id-aqui',
    projectId: 'seu-project-id-aqui',
    storageBucket: 'seu-storage-bucket-aqui',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'sua-api-key-aqui',
    appId: 'seu-app-id-aqui',
    messagingSenderId: 'seu-messaging-sender-id-aqui',
    projectId: 'seu-project-id-aqui',
    storageBucket: 'seu-storage-bucket-aqui',
    iosClientId: 'seu-ios-client-id-aqui',
    iosBundleId: 'seu-ios-bundle-id-aqui',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3jRyvOZplILEl99UHUHuMYC2182ZKTZA',
    appId: '1:129048992702:ios:e920482b2f3c2c4f16f7ef',
    messagingSenderId: '129048992702',
    projectId: 'ohabito-1c8c6',
    storageBucket: 'ohabito-1c8c6.appspot.com',
    iosClientId: '129048992702-8vng5kj00p3qcobgc1a0m9kbghsc3s4k.apps.googleusercontent.com',
    iosBundleId: 'com.example.ohabito',
  );
}
